### PR TITLE
fix(task): fix update task to append-only

### LINKED ISSUE #16: Add (append) content to an existing page
### Feature description

Currently, the functionality deletes (archives) all existing page content and updates the page with new content. It would be great to instead append content to the bottom of the existing page.

* https://developers.notion.com/reference/patch-page#adding-content-to-a-page
* https://developers.notion.com/reference/patch-block-children

### PR DESCRIPTION
**Pull request by Ben8t**
Here is QA, @akeller lmk if it matchs what you expected :)

https://jam.dev/c/36727654-be00-4600-bd5a-640704426efc

### CODE REVIEW

**Review by akeller — APPROVED** [review]
This is exactly what I was expecting! Thanks for updating the docs too. 🚀

File: src/main/java/io/kestra/plugin/notion/page/Update.java [hunk 1]
```diff
@@ -180,27 +177,10 @@ private NotionResponse updatePageTitle(RunContext runContext, String pageId, Str
...
-            for (Map<String, Object> block : childrenResponse.getChildren()) {
-                String blockId = (String) block.get("id");
-                if (blockId != null) {
-                    archiveBlock(runContext, blockId);
-                }
-            }
-        }
-        
-        // Step 3: Add new blocks from markdown
+    private void appendPageContent(RunContext runContext, String pageId, String newContent) throws Exception {
```
Comment (fdelbrayelle) [inline src/main/java/io/kestra/plugin/notion/page/Update.java]: @Ben8t Maybe update unit tests to ensure this behavior is validated 👍

Comment (Ben8t) [reply src/main/java/io/kestra/plugin/notion/page/Update.java]: https://github.com/kestra-io/plugin-notion/pull/21/commits/3debaed0a1697d3dc8c3f8000891c51f8d8e3931
